# Simple Core Deployment Configuration for Kasplex Testnet

owner: "0x4f0b4c4c23E31f3e5bCCEfFb649AfdE964B7dF50"

# Default ISM - using trusted relayer
defaultIsm:
  type: trustedRelayerIsm
  relayer: "0x4f0b4c4c23E31f3e5bCCEfFb649AfdE964B7dF50"

# Default Hook - merkle tree
defaultHook:
  type: merkleTreeHook

# Required Hook - protocol fee
requiredHook:
  type: protocolFee
  owner: "0x4f0b4c4c23E31f3e5bCCEfFb649AfdE964B7dF50"
  beneficiary: "0x4f0b4c4c23E31f3e5bCCEfFb649AfdE964B7dF50"
  maxProtocolFee: "100000000000000000"
  protocolFee: "0"

# Proxy Admin configuration
proxyAdmin:
  owner: "0x4f0b4c4c23E31f3e5bCCEfFb649AfdE964B7dF50"
